### PR TITLE
test all sources every night

### PR DESCRIPTION
**Pull request by AstrakhantsevaAA**
# Tell us what you do here

- [ ] implementing verified source (please link a relevant issue labelled as `verified source`)
- [x] fixing a bug (please link a relevant bug report)
- [ ] improving, documenting, customizing existing source (please link an issue or describe below)
- [ ] anything else (please link an issue or describe below)

# Relevant issue

issue #

# More PR info

We need to check all our verified sources sometimes. We test them, but only when create or change them.  They break silently all the time, and we find out about it from users or by accident.

Suggestion: we could have a nightly run, every night at 4am or so

### CODE REVIEW

**Review by burnash — APPROVED** [review]
Awesome work, @AstrakhantsevaAA

**Comment by rudolfix** [comment]
@AstrakhantsevaAA run this only on duckdb on linux.

**Comment by burnash** [comment]
@AstrakhantsevaAA one more thing: we need to exclude some tests from nightly tests. We can do that using custom pytest markers: https://docs.pytest.org/en/7.1.x/example/markers.html

**Comment by VioletM** [comment]
@AstrakhantsevaAA maybe it makes sense to merge this even before all tests are up and running? This way we would see the stats on failing tests

**Comment by AstrakhantsevaAA** [comment]
@burnash I skip tests without stable test account [here](https://github.com/dlt-hub/verified-sources/pull/379)
@VioletM now we're waiting for only Kafka test, so I think now it makes sense to merge it. 
@rudolfix OK

**Review by sultaniman — APPROVED** [review]

**Pull request merged**
