### PR TITLE
feat(github): add stargazers

### PR DESCRIPTION
**Pull request by cybermaxs**
### Tell us what you do here

- [x] improving, documenting, or customizing an existing source (please link an issue or describe below)

### Short description

This PR adds a new resource for github stargazers. It provides the github user info (login, url, avatar) and the starred_at for every repo. The data is fetched using graphql and the full history is available.

### Related Issues
not related to any issue

### Additional Context

- not related to this PR but I was not able to install the pre-requisites with python 3.12 : multidict is not compatible, so I have moved to 3.8 as suggested by the contribution guideline
- unfortunately it is not possible to get forks/watchers with date from github graphql api

### CODE REVIEW

**Comment by cybermaxs** [comment]
🤔 Should I include the repository url in the response ?

**Comment by rudolfix** [comment]
> 🤔 Should I include the repository url in the response ?

hmmm I think not. the request is for particular repository so we do not need to tell which repository it is for each item. users can add this info themselves using `add_map` on the stargazers resource

**Review by rudolfix — APPROVED** [review]
this is good! I enabled CI for this PR and all tests are passing. there are some linting errors. ping me if you are able to run mypy (see Makefile). if not we can fix it as well!

thanks for contribution!

**Comment by cybermaxs** [comment]
> this is good! I enabled CI for this PR and all tests are passing. there are some linting errors. ping me if you are able to run mypy (see Makefile). if not we can fix it as well!
> 
> thanks for contribution!

I'll take a look, but I don't think this is related to my changes

**Comment by rudolfix** [comment]
@cybermaxs you are right! I reran the CI and all is green now!

**Pull request merged**
